config/routes.rb
Rails.application.routes.draw do

  # route the site root to home index
  root :to => 'home#index'

  match '/', :to => "home#index", :as => :home_index, :via => :get
  match '/home', :to => "home#home", :as => :home, :via => :get
  match '/index', :to => "home#index", :as => :home_page_index, :via => :get
  match '/modal-test', :to => "home#modal_test", :as => :modal_test, :via => :get

  match '/home-new', :to => "home#home_new", :as => :home_new, :via => :get

  match '/search/:q', :to => "search#index", :as => :search, :via => :get
  match '/search-term/:q/:num', :to => "search#search_term", :as => :search_term, :via => :get

  match '/video', :to => "home#video", :as => :video, :via => :get

  match '/video-take-over', :to => "video#index", :as => :video_take_over, :via => :get

  match '/resources', :to => "resources#index", :as => :resources, :via => :get
  match '/resources/tag/:tag', :to => "resources#load_tags", :as => :load_tags, :via => :get
  match '/resources/:id', :to => "resources#show_resource", :as => :show_resource, :via => :get

  match '/resources/cat/:category', :to => "resources#load_cats", :as => :load_cats, :via => :get
  match '/resources/all/:all', :to => "resources#all_resources", :as => :all_resources, :via => :get
  match '/resources/category/:category', :to => "resources#category_result", :as => :category_result, :via => :get
  match '/resources/content-type/:id', :to => "resources#type_result", :as => :type_result, :via => :get

  match '/about/customers', :to => "company#customers", :as => :customers, :via => :get

  match '/about/overview', :to => "company#overview", :as => :overview, :via => :get

  match '/about/analyst-reviews', :to => "company#analyst_reviews", :as => :analyst_reviews, :via => :get

  #match '/contact', :to => "company#contact", :as => :contact, :via => :get

  #match '/support', :to => "company#support", :as => :support, :via => :get

  match '/about/contact', :to => "company#contact", :as => :contact, :via => :get

  match '/about/technology-partners', :to => "company#technology_partners", :as => :technology_partners, :via => :get

  match '/events', :to => "company#events", :as => :events, :via => :get

  match '/elementx', :to => "solutions#elementx", :as => :elementx, :via => :get

  match '/infrastructure-continuum', :to => "solutions#infrastructure_continuum", :as => :infrastructure_continuum, :via => :get

  match '/developers', :to => "developers#index", :as => :developers_index, :via => :get

  match '/gmq-lp', :to => "landing_pages#gmq", :as => :gmq, :via => :get

  match '/gmq-lp-b', :to => "landing_pages#gmq_lp_b", :as => :gmq_b, :via => :get

  match '/lp-ebook-getting-it-right-openstack-private-cloud-storage', :to => "landing_pages#openstack_getting_it_right", :as => :openstack_getting_it_right, :via => :get

  match '/lp-storage-mrd-template', :to => "landing_pages#storage_mrd_template", :as => :storage_mrd_template, :via => :get

  match '/esg', :to => "landing_pages#esg", :as => :esg, :via => :get

  match '/openstack-summit-vancouver', :to => "landing_pages#openstack_summit_vancouver", :as => :openstack_summit_vancouver, :via => :get

  match '/404', :to => "errors#error_404", :as => :error_404, :via => :all

  match '/flash-array-guides/:id', :to => "flash_array_guides#show_guide", :as => :organic_landing_page, :via => :get

  match '/news', :to => "news#index", :as => :news, :via => :get

  match '/press-releases/', :to => "press_release#index", :as => :pr_index, :via => :get

  match '/press-releases/:id', :to => "press_release#show_pr", :as => :show_pr, :via => :get

  match '/analyst-day-2016', :to => "landing_pages#analyst_day_2016", :as => :analyst_day_2016, :via => :get
  match '/lp-static/cisco-live-berlin', :to => "landing_pages#cisco_live_berlin", :as => :cisco_live_berlin, :via => :get

  match '/greatfeats', :to => "great_feats#index", :as => :great_feats, :via => :get
  match '/greatfeats/:id', :to => "great_feats#show_great_feats", :as => :show_great_feat, :via => :get
  match '/greatfeats/thank-you/:id', :to => "great_feats#thank_you", :as => :great_feats_thank_you, :via => :get
  match '/greatfeats/form/:id', :to => "great_feats#form", :as => :great_feats_form, :via => :get
  match '/greatfeats/form/:id/:type', :to => "great_feats#form", :as => :great_feats_form_mobile, :via => :get

  match '/lp-static/five-ways-your-storage-vendor-is-costing-you-more-than-you-think', :to => "landing_pages#five_ways_your_storage_vendor_is_costing_you_more_than_you_think", :as => :five_ways_your_storage_vendor_is_costing_you_more_than_you_think, :via => :get

  match '/lp-static/cisco-live', :to => "landing_pages#cisco_live", :as => :cisco_live, :via => :get
  match '/lp-static/idc', :to => "landing_pages#idc", :as => :idc, :via => :get
  match '/lp-static/comparing-flash-storage-platforms', :to => "landing_pages#comparing_flash_storage_platforms", :as => :architectural_comparisons, :via => :get
  match '/lp-static/sp-benchmark', :to => "landing_pages#sp_benchmark", :as => :sp_benchmark, :via => :get
  match '/lp-static/sp-benchmark-german', :to => "landing_pages#sp_benchmark_german", :as => :sp_benchmark_german, :via => :get
  match '/lp-static/sp-benchmark-fr', :to => "landing_pages#sp_benchmark_french", :as => :sp_benchmark_french, :via => :get

  match '/lp-static/dell-training-lp', :to => "landing_pages#denver_metro_solidfire_sales_training_dell", :as => :denver_metro_solidfire_sales_training_dell, :via => :get

  match '/lp/unstoppable', :to => "landing_pages#unstoppable", :as => :unstoppable, :via => :get

  get '/may-the-flash-be-with-you', to: redirect('/')
  get '/may-the-flash-be-with-you-cambridge-computer', to: redirect('/')

  match '/may-the-flash-be-with-you-field', :to => "landing_pages#may_the_flash_be_with_you_field", :as => :flash_be_with_you_field, :via => :get

  match '/lp/:id', :to => "lp#index", :as => :custom_landing, :via => :get

  match '/netapp-sales', :to => "lp#index", :as => :netapp_sales, :via => :get, :id => 'netapp-sales'

  match '/flash-forward', :to => "storage_system#flash_forward", :as => :flash_forward, :via => :get

  match '/gmq-video', :to => "video#index", :as => :gmq_video, :via => :get

  match '/elementos', :to => "landing_pages#element_os_8", :as => :element_os_8, :via => :get


  match '/about/channel-partners', :to => "company#channel_partners", :as => :channel_partners, :via => :get

  match '/about/careers', :to => "company#careers", :as => :careers, :via => :get
  match '/about/careers/team/:id', :to => "company#team", :as => :team, :via => :get
  match '/about/careers/jobs', :to => "company#jobs", :as => :jobs, :via => :get

  match '/style-guide', :to => "style_guide#index", :as => :style_guide, :via => :get

  match '/about/request-access-form', :to => "company#request_access_form", :as => :request_access_form, :via => :get

  match '/solutions', :to => "solutions#solutions_overview", :as => :solutions_overview, :via => :get
  match '/solutions/cloud-orchestration', :to => "solutions#cloud_orchestration", :as => :cloud_orchestration, :via => :get
  match '/solutions/cloud-orchestration/openstack', :to => "solutions#openstack", :as => :openstack, :via => :get
  match '/solutions/cloud-orchestration/cloudstack', :to => "solutions#cloudstack", :as => :cloudstack, :via => :get
  match '/solutions/cloud-orchestration/flexiant', :to => "solutions#flexiant", :as => :flexiant, :via => :get
  match '/solutions/cloud-orchestration/onapp', :to => "solutions#onapp", :as => :onapp, :via => :get
  match '/solutions/database', :to => "solutions#database", :as => :database, :via => :get
  match '/solutions/database/oracle', :to => "solutions#oracle", :as => :oracle, :via => :get
  match '/solutions/database/mysql', :to => "solutions#mysql", :as => :mysql, :via => :get
  match '/solutions/database/mssql', :to => "solutions#mssql", :as => :mssql, :via => :get
  match '/solutions/database/mongodb', :to => "solutions#mongodb", :as => :mongodb, :via => :get
  match '/solutions/vdi', :to => "solutions#vdi", :as => :vdi, :via => :get
  match '/solutions/vdi/citrix-xendesktop', :to => "solutions#citrix_xen_desktop", :as => :citrix_xen_desktop, :via => :get
  match '/solutions/vdi/vmware-horizon-view', :to => "solutions#vmware_horizon_view", :as => :vmware_horizon_view, :via => :get
  match '/solutions/agile-infrastructure/openstack', :to => "solutions#openstack_infrastructure", :as => :openstack_infrastructure, :via => :get
  match '/solutions/vmware-solutions/', :to => "solutions#vmware_solutions", :as => :vmware_solutions, :via => :get
  match '/solutions/competitive-comparison', :to => "solutions#competitive_comparison", :as => :competitive_comparison, :via => :get
  match '/solutions/data-protection', :to => "solutions#data_protection", :as => :data_protection, :via => :get
  match '/solutions/service-providers', :to => "solutions#service_providers", :as => :service_providers, :via => :get
  match '/solutions/success-stories', :to => "solutions#success_stories", :as => :success_stories, :via => :get
  match '/solutions/service-providers/managed-dedicated-san/', :to => "solutions#managed_dedicated_san", :as => :managed_dedicated_san, :via => :get
  match '/solutions/service-providers/infrastructure-as-a-service/', :to => "solutions#infrastructure_as_a_service", :as => :infrastructure_as_a_service, :via => :get
  match '/solutions/service-providers/desktop-as-a-service/', :to => "solutions#desktop_as_a_service", :as => :desktop_as_a_service , :via => :get
  match '/solutions/service-providers/database-as-a-service/', :to => "solutions#database_as_a_service", :as => :database_as_a_service , :via => :get
  match '/solutions/case-studies/:id', :to => "solutions#case_studies", :as => :case_studies , :via => :get
  match '/solutions/agile-infrastructure', :to => "solutions#agile_infrastructure", :as => :agile_infrastructure, :via => :get

app/controllers/cms/home_controller.rb
class Cms::HomeController < Cms::BaseController
  before_filter :check_login
  before_filter :get_cms_login_details

  layout 'cms'

  def index

    if (@user.is_admin == 1)
      available_sections = Cms::Section.all
      @non_admin_sections = []
      @admin_sections = []
      @resource_sections = []

      available_sections.each do |section|
        if section.title == "Project Request Items" || section.title == "CMS Sections" || section.title == "Users" || section.title == "Resource Types" || section.title == "Resource Categories" || section.title =="Project Request Status" || section.title == "Project Request Types"
          @admin_sections << section
        else
          find_resource_and_non_admin_sections(section)
        end
      end

    else
      unless @user.sections.nil?
        available_sections = Cms::Section.find(@user.sections)
        @non_admin_sections = []
        @resource_sections = []

        available_sections.each do |section|
          find_resource_and_non_admin_sections(section)
        end
      end
    end
  end

  private

  def find_resource_and_non_admin_sections(section)
    if section.title == 'Resources' || section.title == 'Resource Images'
      @resource_sections << section
    elsif section.title == 'Project Request'
      @project_request_section = section
    else
      @non_admin_sections << section
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

    set_meta_tags :title => 'SolidFire + NetApp = Unstoppable All-Flash Storage',
                  :description => 'SolidFire is the industry’s most complete all-flash storage system and Gartner’s highest-rated solid-state array for overall use, two years in a row.',
                  :canonical => 'http://www.solidfire.com/'

    @news = Cms::News.all.order_by(:pub_date.desc).first

    @getMonthYearDate = Date.today.strftime("%Y-%m-%d")

    @events = Cms::Event.where(:start_date.gte => @getMonthYearDate).order_by(:start_date.asc).first

    if !@events
      @events = Cms::Event.order_by(:start_date.asc).last
    end

  end

  def home

  end

  def home_new
    set_meta_tags :title => 'All-Flash Array for Next-Generation Data Centers | SolidFire',
                  :description => 'High performance all-flash array designed for public and private clouds. Deliver new applications and capabilities faster with SolidFire.',
                  :canonical => 'http://www.solidfire.com/'

    @pr = Cms::PressRelease.all.order_by(:pub_date.desc).limit(1)

    @resources = Cms::Resource.where(:order_id.ne => 'false').order_by(:order_id.asc).limit(2)

    @news = Cms::News.all.order_by(:pub_date.desc).limit(1)
  end

  def home_new_updated
    set_meta_tags :title => 'All-Flash Array for Next-Generation Data Centers | SolidFire',
                  :description => 'High performance all-flash array designed for public and private clouds. Deliver new applications and capabilities faster with SolidFire.',
                  :canonical => 'http://www.solidfire.com/'

    @pr = Cms::PressRelease.all.order_by(:pub_date.desc).limit(1)

    @resources = Cms::Resource.where(:order_id.ne => 'false').order_by(:order_id.asc).limit(2)

    @news = Cms::News.all.order_by(:pub_date.desc).limit(1)
  end

  def modal_test

    render :layout => false
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/home.html.haml
.container
  %h1 The 10 column complex nested grid AG test
  .ag.ag1
    %h2 AG1

  .ag.ag2
    %h2 AG 2
    .ag.ag4
      %h2 AG 4
    .ag.ag5
      %h2 AG 5
    .ag.ag6
      %h2 AG 6

    .ag.ag7
      %h2 AG 7
      .ag.ag8
        %h2 AG 8
      .ag.ag9
        %h2 AG 9
      .ag.ag10
        %h2 AG 10

  .ag.ag3
    %h2 AG 3

app/views/home/home_new.html.haml
-# .slider-wrapper
-#  .slider.slider1
-#    #VMworld-slider
-#      .container
-#        %p{:style => 'color:#FFF;text-align:center;'}
-#          Join us at VMworld 2015 &#149; Aug 30-Sept 3 &#149; San Francisco &#149; Booth #92
.home-section-one-two
  .home-container
    .hero-home-node
      = image_tag 'home/hero-home-node.png', :alt => 'SolidFire Flash Array'
  .home-section-one
    .home-container.page-top-margin
      .home-section-one--copy-area
        %h1
          THE INDUSTRY'S HIGHEST-RATED ALL-FLASH ARRAY &#42;
          %span Two years in a row.
        %p
          The most complete feature set with the broadest range of next generation capabilities.
          %br
          SolidFire is scale-out, all-flash storage for the modern data center.
        %p
          = link_to 'why is SolidFire the ultimate all-flash array?', '#', :class => 'button--default-styles button--white'
      .home-section-one--form-content
        .home-section-one--form-content--form-container
          .home-section-one--form-content--form-container--header
            Free 2015 Gartner reports
            %br
            on solid-state arrays
          %script(src ='//app-ab03.marketo.com/js/forms2/js/forms2.min.js')
          %form{:id => 'mktoForm_2759'}
          :javascript
              MktoForms2.loadForm("//app-ab03.marketo.com", "538-SKP-058", 2759);
  .home-section-two
    .home-section-two-slant
    .home-container
      .why-solidfire-leader
        %h2 What SolidFire all-flash storage does
        %p
          Start you all-flash evaluation here. Download comprehensive architectural comparisons about how SolidFire's innovative scale-out, all-flash platform compares to XtremIO, Pure Storage, and Netapp.
      .industry-complete-feature-set-wrapper
        .industry-complete-feature-set
          %h5
            The industry's Most Complete
            %br
            Feature Set
          %p
            Get all the features you need from storage —  real-time replication, global data efficiencies, broad integrations, end-to-end security, and more.
          %p
            %a{:href => '#'}
              See all features &#187;
        .industry-complete-feature-set-features
          .industry-complete-feature-set-features--item
            .plus-circle-wrapper
              .plus-circle-item
                &#43;
            %h5
              Scale-Out Agility
            %p
              Add nodes without disrupting existing workloads, and respond more rapidly and predictably to changing infrastructure demands.
          .industry-complete-feature-set-features--item
            .plus-circle-wrapper
              .plus-circle-item
                &#43;
            %h5
              Guaranteed Performance
            %p
              Ensure every application has 100% predictable performance, even in the most complex, multi-application environments.
          .industry-complete-feature-set-features--item
            .plus-circle-wrapper
              .plus-circle-item
                &#43;
            %h5
              Complete Automation
            %p
              Automate all your storage provisioning, management, monitoring, and reporting tasks with the industry’s simplest and most complete REST-based API.

.home-section-three
  .home-container
    .flash-forward-container
      .flash-forward
        = image_tag 'home/flash-forward-program.png'
        %p
          Eliminate storage refresh cycles, compatibility concerns, and drive wear for good.
        %p
          %a{:href => '#', :class => 'button--red'}
            Find out more. &#187;
    .lab-whitepaper-container
      .right-half-bg-color
      .lab-whitepaper-container-absolute
        = image_tag 'home/esg-whitepaper.png'
        %p
          "SolidFire
          %span
            Automation
          can help lower
          %br
          operating expenses by up to 67%."
        %p
          %a{:href => '#', :class => 'button--red'}
            See the full report &#187;
.home-section-four
  .home-container
    .home-section-four-wrapper
      .whats-new-wrapper
        .whats-new-title
          %h3
            What's new?
        .whats-new-item
          .whats-new-item--icon
            %i{:class => 'icon-NewsPress icon-whats-new'}
          - @pr.each do |result|
            .whats-new-item--content
              .whats-new-item--title
                %h5
                  = result.title
              .whats-new-item--body
                = result.sub_title
              .whats-new-item--read-more
                %a{:href => result.short_url}
                  read more &#62;
        - @resources.each do |re|
          .whats-new-item
            .whats-new-item--icon
              %i{:class => 'icon-Resources icon-whats-new'}
            .whats-new-item--content
              .whats-new-item--title
                %h5
                  = re.title
              .whats-new-item--body
                = re.description
              .whats-new-item--read-more
                %a{:href => '/resources/' + re.slugs[0]}
                  read more &#62;
        .whats-new-item
          .whats-new-item--icon
            %i{:class => 'icon-Blog2 icon-whats-new'}
          .whats-new-item--content
            .whats-new-item--title.blog-title
            .whats-new-item--blog
              .blog-date
              .blog-author
            .whats-new-item--read-more
              %a{:href => '', :class => 'blog-link'}
                read more &#62;
      .event-wrapper
        .events-title
          %h3
            Join us at VMworld
        .event-details-date
          August 30 - September 3 | Booth #929
        .event-details-body
          %p VMworld, hosted by VMware, is a global event with two VMworld Campuses - San Francisco and Barcelona.
          %p At VMworld you'll gain the tools you need to transform conventional remedies into seamless, agile solutions that dramatically simplify your operations and provide unmatched business advantages. Join us as thousands of IT innovators explore the leading edge of the industry's most powerful trends.
          %p See SolidFire at booth #929
          %p
            %a{:href => vmworld_path, :class => 'button--red'}
              join us &#187;
.home-section-five
  .home-container
    %h3
      The world's most agile data centers demand SolidFire all-flash storage
    .customers-wrapper
      = link_to image_tag( 'home/home-page-customer-logos.png'), 'http://www.solidfire.com/about/customers/'

app/views/home/index.html.haml
= content_for :head do
  = stylesheet_link_tag 'home', :media => 'all'

= content_for :javascript do
  = javascript_include_tag 'index'
  = javascript_include_tag 'jquery.flip.min'

.home-section-one
  .home-container.page-top-margin
    .home-section-one--full-racks.fade-in-three
      = image_tag 'home/HomeDoubleRack.png', class: 'banner-nodes'
    .home-section-one--content
      .slide-up
        %h1
          The world’s most complete all-flash array
        = link_to 'Storage Automation report', '/resources/2015-storage-automation-report', class: 'button-red red-changes', :id => '2015-storage-automation-report'
        = link_to 'solidfire vs emc & pure', custom_landing_path('comparing-flash-storage-platforms'), class: 'button-white-outline press-link', :id => 'pr'
.home-section-two
  .home-container
    .home-section-two--item-wrapper
      .fit-container-relative
        %i.icon-ScaleOutNew
      %h4 Scale-out effortlessly
      %p
        Increase infrastructure agility and responsiveness by delivering capacity and performance on demand.
      %p
        No more data migrations, RAID management, storage silos, disruptions, downtime... and the list goes on and on.
      .fit-container.item-wrapper-red
        %a{:href => scale_out_path}
          learn how we do it
          %span &#187
    .home-section-two--item-wrapper
      .fit-container
        %i.icon-ProvisionIcon
      %h4 Automate everything
      %p
        Deploy applications, services, and all your VMs up to 15x faster than with traditional architectures.
      %p
        Do away with menial, manual, and overhead storage tasks. See if your business can keep up with you.
      .fit-container.item-wrapper-red
        %a{href: automated_management_path}
          plug into our api
          %span  &#187
    .home-section-two--item-wrapper--last
      .fit-container-relative
        %i.icon-GuaranteedTotalPerf
      %h4 Guarantee total performance
      %p
        Deliver predictable performance to hundreds of applications on a single platform &#151; every single time.
      %p
        Stop wasting time looking for performance problems or bottlenecks. With SolidFire, you won't find them.
      .fit-container.item-wrapper-red
        %a{href: guaranteed_performance_path}
          see how we make it possible
          %span  &#187
.angle-section-0
  .section-under-left.red-under
  .section-top-left
    .home-container
      .content
        .skew-fix-left
          .fit-container-relative
            %h2
              Proven in the world's most demanding data centers
          .fit-container-relative.customer-logos
            .paypal-image
              = image_tag 'home/paypal-logo.png'
            .ebay-image
              = image_tag 'home/ebay-logo.png'
            .endicia-image
              = image_tag 'home/endicia-logo.png'
            .sungard-image
              = image_tag 'home/sungard-logo.png', :class => 'sungard'
            .ezverify-image
              = image_tag 'home/ezverify-logo.png'
          .fit-container-relative
            .learn-how
              %a{href: customers_path}
                learn how we did it
                %span &#187;

.home-section-three
  .home-container
    .fit-container-relative
      %h2.no-margin-top.investment
        The ultimate investment protection
    .fit-container-relative
      .span6
        = image_tag 'home/flash-forward-program.png'
        %p
          Eliminate storage refresh cycles, compatibility concerns, and drive wear for good.
        %p
          %a{href: flash_forward_path, class: 'button-red'}
            find out more
            %span  &#187;

      .span6right
        = image_tag 'home/whitepaper3Dhm2.png'
        %p
          Lower operating expenses up to 67% with SolidFire automation.
          %strong ESG 2015
        %p
          %a{href: 'http://www.solidfire.com/esg', class: 'button-red', target: '_blank'}
            see the full report
            %span  &#187;
.angle-section-1
  .section-under-left
  .section-top-left.off-white-top
    .home-container
      .skew-fix-left
        .content
          .fit-container-relative
            %h2.no-margin-top.happening
              Happening now
          .home-section-two--item-wrapper
            .fit-container-relative
              %i.icon-BlogP1
            %h4.blog-title
            %span.blog-author
            %br
            %span.blog-date
            .fit-container.item-wrapper-red
              %a.blog-link{:href => 'http://www.solidfire.com/blog/interview-with-john-griffith-what-are-docker-and-containers-all-about/', :target => '_blank'}
                read more
                %span
                  &#187;
          .home-section-two--item-wrapper
            .fit-container
              %i.icon-EventP1
            - if @events
              %h4= @events.title
              %span
                = @events.location
                %br
                = @events.start_date.strftime("%b %d") + (@events.start_date == @events.end_date ? '' : ' - ' + @events.end_date.strftime("%d"))
              .fit-container.item-wrapper-red
                %a{:href => @events.cta_url, :target => '_blank'}
                  read more
                  %span
                    &#187;
          .home-section-two--item-wrapper--last
            .fit-container-relative
              %i.icon-BlogP1
            %h4= @news.title
            %span
              Publication:
              = @news.publication
              %br
              = @news.pub_date.strftime("%b %d")
            .fit-container.item-wrapper-red
              %a{:href => @news.url_shorten, :target => '_blank'}
                read more
                %span
                  &#187;
.home-section-four
  .home-container
    %h2.no-margin-top Results that speak for themselves
    .span12
      .span4
        #home-card-one
          .front
            = image_tag 'home/ulitmatelogo.png', :class => 'ultimate-logo'
            %p "The performance is night and day compared to our older environments."
          .back
            %ul
              %li Improved IOPS performance 4x
              %li Enabled fast, easy recoverability
              %li VMware and OpenStack private cloud
            %a{:href => customers_path, :class => 'button-white-outline'} learn more

      .span4middle
        #home-card-two
          .front
            = image_tag 'home/puc.png', :class => 'cal-logo'
            %p "SolidFire enabled us to tackle our pain point: virtualizing that last 20% of high-IOPS applications."
          .back
            %ul
              %li Virtualized last 20% of workloads
              %li Reduced footprint from 21U to 4U
              %li Improved performance 25% to 30%
            %a{:href => customers_path, :class => 'button-white-outline'} learn more

      .span4last
        #home-card-three
          .front
            = image_tag 'home/1.1.png', :class => 'one-logo'
            %p "We can now offer two million server configurations in 55 seconds; a massive improvement for our users."
          .back
            %ul
              %li Guaranteed customer performance
              %li Reduced storage complexity
              %li Dramatically improved flexibility
            %a{:href => customers_path, :class => 'button-white-outline'} learn more

app/views/home/modal_test.html.haml
%html
  %head

    %link{:rel => 'stylesheet', :href => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/css/bootstrap.min.css'}
    %script{:src => 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js'}
    %script{:src => 'https://maxcdn.bootstrapcdn.com/bootstrap/3.3.2/js/bootstrap.min.js'}
    %script{:src => 'http://munchkin.marketo.net/munchkin.js', :type => 'text/javascript'}
  %body
    %button{:type => 'button', :class => 'btn btn-primary btn-lg', :data => {:toggle => 'modal', :target => '#myModal'}}
      Launch video modal
    #myModal.modal.fade{:tabindex => '-1', :role => 'dialog', :aria => {:labelledby => 'myModalLabel', :hidden => 'true'}}
      .modal-dialog
        .modal-content
          .modal-header
            %button{:type => 'button', :class => 'close', :data => {:dismiss => 'modal'}, :aria => {:label => 'close'}}
              %span{:aria => {:hidden => 'true'}}
                &times;
          .modal-body
            #player-wrapper{:style => 'width:100%;float:left;'}
              #player
              :javascript
                var tag = document.createElement('script');

                tag.src = "https://www.youtube.com/iframe_api";
                var firstScriptTag = document.getElementsByTagName('script')[0];
                firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);

                var player;
                function onYouTubeIframeAPIReady() {
                player = new YT.Player('player', {
                height: '390',
                width: '640',
                videoId: 'zpeQqLNzwjw',
                events: {
                'onReady': onPlayerReady,
                'onStateChange': onPlayerStateChange
                }
                });}

                $('.modal-content').css('width',(640 + 30) + 'px')

                function onPlayerReady(event) {
                }

                var done = false;
                function onPlayerStateChange(event) {
                if (event.data == YT.PlayerState.PLAYING && !done) {
                mktoMunchkin("538-SKP-058");
                mktoMunchkinFunction('visitWebPage', {
                url: '/{{my.videoplayURL:default=DefaultVideo}}/play', params: 'x=y&2=3'
                });
                }
                }
          .modal-footer
            %button.btn.btn-default{:type => 'button', :data => {:dismiss => 'modal'} }
              close

app/views/home/video.html.haml
- content_for :javascript do
  = javascript_include_tag "froogaloop2.min"
.video-page__container
  .video-container
    .h_iframe{:style => 'display:block;'}
      .close-btn
        = link_to image_tag( 'home/close-button.png'), 'javascript://', :class => 'close-video'
      %iframe{:frameborder => "0", :src => "//player.vimeo.com/video/153854468?autoplay=1&api=1&player_id=gmq-video", :allowfullscreen => true, :mozallowfullscreen => true, :webkitallowfullscreen => true, :id => "gmq-video"}
      .div-overlay