config/routes.rb
Rails.application.routes.draw do

  # route the site root to home index
  root :to => 'home#index'

  match '/', :to => "home#index", :as => :home_index, :via => :get
  match '/home', :to => "home#home", :as => :home, :via => :get
  match '/index', :to => "home#index", :as => :home_page_index, :via => :get
  match '/modal-test', :to => "home#modal_test", :as => :modal_test, :via => :get

  match '/home-new', :to => "home#home_new", :as => :home_new, :via => :get

  match '/search/:q', :to => "search#index", :as => :search, :via => :get
  match '/search-term/:q/:num', :to => "search#search_term", :as => :search_term, :via => :get

  match '/video', :to => "home#video", :as => :video, :via => :get

  match '/video-take-over', :to => "video#index", :as => :video_take_over, :via => :get

  match '/resources', :to => "resources#index", :as => :resources, :via => :get
  match '/resources/tag/:tag', :to => "resources#load_tags", :as => :load_tags, :via => :get
  match '/resources/:id', :to => "resources#show_resource", :as => :show_resource, :via => :get

  match '/resources/cat/:category', :to => "resources#load_cats", :as => :load_cats, :via => :get
  match '/resources/all/:all', :to => "resources#all_resources", :as => :all_resources, :via => :get
  match '/resources/category/:category', :to => "resources#category_result", :as => :category_result, :via => :get
  match '/resources/content-type/:id', :to => "resources#type_result", :as => :type_result, :via => :get

  match '/about/customers', :to => "company#customers", :as => :customers, :via => :get

  match '/about/overview', :to => "company#overview", :as => :overview, :via => :get

  match '/about/analyst-reviews', :to => "company#analyst_reviews", :as => :analyst_reviews, :via => :get

  #match '/contact', :to => "company#contact", :as => :contact, :via => :get

  #match '/support', :to => "company#support", :as => :support, :via => :get

  match '/about/contact', :to => "company#contact", :as => :contact, :via => :get

  match '/about/technology-partners', :to => "company#technology_partners", :as => :technology_partners, :via => :get

  match '/events', :to => "company#events", :as => :events, :via => :get

  match '/elementx', :to => "solutions#elementx", :as => :elementx, :via => :get

  match '/infrastructure-continuum', :to => "solutions#infrastructure_continuum", :as => :infrastructure_continuum, :via => :get

  match '/developers', :to => "developers#index", :as => :developers_index, :via => :get

  match '/gmq-lp', :to => "landing_pages#gmq", :as => :gmq, :via => :get

  match '/gmq-lp-b', :to => "landing_pages#gmq_lp_b", :as => :gmq_b, :via => :get

  match '/lp-ebook-getting-it-right-openstack-private-cloud-storage', :to => "landing_pages#openstack_getting_it_right", :as => :openstack_getting_it_right, :via => :get

  match '/lp-storage-mrd-template', :to => "landing_pages#storage_mrd_template", :as => :storage_mrd_template, :via => :get

  match '/esg', :to => "landing_pages#esg", :as => :esg, :via => :get

  match '/openstack-summit-vancouver', :to => "landing_pages#openstack_summit_vancouver", :as => :openstack_summit_vancouver, :via => :get

  match '/404', :to => "errors#error_404", :as => :error_404, :via => :all

  match '/flash-array-guides/:id', :to => "flash_array_guides#show_guide", :as => :organic_landing_page, :via => :get

  match '/news', :to => "news#index", :as => :news, :via => :get

  match '/press-releases/', :to => "press_release#index", :as => :pr_index, :via => :get

  match '/press-releases/:id', :to => "press_release#show_pr", :as => :show_pr, :via => :get

  match '/analyst-day-2016', :to => "landing_pages#analyst_day_2016", :as => :analyst_day_2016, :via => :get
  match '/lp-static/cisco-live-berlin', :to => "landing_pages#cisco_live_berlin", :as => :cisco_live_berlin, :via => :get

  match '/greatfeats', :to => "great_feats#index", :as => :great_feats, :via => :get
  match '/greatfeats/:id', :to => "great_feats#show_great_feats", :as => :show_great_feat, :via => :get
  match '/greatfeats/thank-you/:id', :to => "great_feats#thank_you", :as => :great_feats_thank_you, :via => :get
  match '/greatfeats/form/:id', :to => "great_feats#form", :as => :great_feats_form, :via => :get
  match '/greatfeats/form/:id/:type', :to => "great_feats#form", :as => :great_feats_form_mobile, :via => :get

  match '/lp-static/five-ways-your-storage-vendor-is-costing-you-more-than-you-think', :to => "landing_pages#five_ways_your_storage_vendor_is_costing_you_more_than_you_think", :as => :five_ways_your_storage_vendor_is_costing_you_more_than_you_think, :via => :get

  match '/lp-static/cisco-live', :to => "landing_pages#cisco_live", :as => :cisco_live, :via => :get
  match '/lp-static/idc', :to => "landing_pages#idc", :as => :idc, :via => :get
  match '/lp-static/comparing-flash-storage-platforms', :to => "landing_pages#comparing_flash_storage_platforms", :as => :architectural_comparisons, :via => :get
  match '/lp-static/sp-benchmark', :to => "landing_pages#sp_benchmark", :as => :sp_benchmark, :via => :get
  match '/lp-static/sp-benchmark-german', :to => "landing_pages#sp_benchmark_german", :as => :sp_benchmark_german, :via => :get
  match '/lp-static/sp-benchmark-fr', :to => "landing_pages#sp_benchmark_french", :as => :sp_benchmark_french, :via => :get

  match '/lp-static/dell-training-lp', :to => "landing_pages#denver_metro_solidfire_sales_training_dell", :as => :denver_metro_solidfire_sales_training_dell, :via => :get

  match '/lp/unstoppable', :to => "landing_pages#unstoppable", :as => :unstoppable, :via => :get

  get '/may-the-flash-be-with-you', to: redirect('/')
  get '/may-the-flash-be-with-you-cambridge-computer', to: redirect('/')

  match '/may-the-flash-be-with-you-field', :to => "landing_pages#may_the_flash_be_with_you_field", :as => :flash_be_with_you_field, :via => :get

  match '/lp/:id', :to => "lp#index", :as => :custom_landing, :via => :get

  match '/netapp-sales', :to => "lp#index", :as => :netapp_sales, :via => :get, :id => 'netapp-sales'

  match '/flash-forward', :to => "storage_system#flash_forward", :as => :flash_forward, :via => :get

  match '/gmq-video', :to => "video#index", :as => :gmq_video, :via => :get

  match '/elementos', :to => "landing_pages#element_os_8", :as => :element_os_8, :via => :get


  match '/about/channel-partners', :to => "company#channel_partners", :as => :channel_partners, :via => :get

  match '/about/careers', :to => "company#careers", :as => :careers, :via => :get
  match '/about/careers/team/:id', :to => "company#team", :as => :team, :via => :get
  match '/about/careers/jobs', :to => "company#jobs", :as => :jobs, :via => :get

  match '/style-guide', :to => "style_guide#index", :as => :style_guide, :via => :get

  match '/about/request-access-form', :to => "company#request_access_form", :as => :request_access_form, :via => :get

  match '/solutions', :to => "solutions#solutions_overview", :as => :solutions_overview, :via => :get
  match '/solutions/cloud-orchestration', :to => "solutions#cloud_orchestration", :as => :cloud_orchestration, :via => :get
  match '/solutions/cloud-orchestration/openstack', :to => "solutions#openstack", :as => :openstack, :via => :get
  match '/solutions/cloud-orchestration/cloudstack', :to => "solutions#cloudstack", :as => :cloudstack, :via => :get
  match '/solutions/cloud-orchestration/flexiant', :to => "solutions#flexiant", :as => :flexiant, :via => :get
  match '/solutions/cloud-orchestration/onapp', :to => "solutions#onapp", :as => :onapp, :via => :get
  match '/solutions/database', :to => "solutions#database", :as => :database, :via => :get
  match '/solutions/database/oracle', :to => "solutions#oracle", :as => :oracle, :via => :get
  match '/solutions/database/mysql', :to => "solutions#mysql", :as => :mysql, :via => :get
  match '/solutions/database/mssql', :to => "solutions#mssql", :as => :mssql, :via => :get
  match '/solutions/database/mongodb', :to => "solutions#mongodb", :as => :mongodb, :via => :get
  match '/solutions/vdi', :to => "solutions#vdi", :as => :vdi, :via => :get
  match '/solutions/vdi/citrix-xendesktop', :to => "solutions#citrix_xen_desktop", :as => :citrix_xen_desktop, :via => :get
  match '/solutions/vdi/vmware-horizon-view', :to => "solutions#vmware_horizon_view", :as => :vmware_horizon_view, :via => :get
  match '/solutions/agile-infrastructure/openstack', :to => "solutions#openstack_infrastructure", :as => :openstack_infrastructure, :via => :get
  match '/solutions/vmware-solutions/', :to => "solutions#vmware_solutions", :as => :vmware_solutions, :via => :get
  match '/solutions/competitive-comparison', :to => "solutions#competitive_comparison", :as => :competitive_comparison, :via => :get
  match '/solutions/data-protection', :to => "solutions#data_protection", :as => :data_protection, :via => :get
  match '/solutions/service-providers', :to => "solutions#service_providers", :as => :service_providers, :via => :get
  match '/solutions/success-stories', :to => "solutions#success_stories", :as => :success_stories, :via => :get
  match '/solutions/service-providers/managed-dedicated-san/', :to => "solutions#managed_dedicated_san", :as => :managed_dedicated_san, :via => :get
  match '/solutions/service-providers/infrastructure-as-a-service/', :to => "solutions#infrastructure_as_a_service", :as => :infrastructure_as_a_service, :via => :get
  match '/solutions/service-providers/desktop-as-a-service/', :to => "solutions#desktop_as_a_service", :as => :desktop_as_a_service , :via => :get
  match '/solutions/service-providers/database-as-a-service/', :to => "solutions#database_as_a_service", :as => :database_as_a_service , :via => :get
  match '/solutions/case-studies/:id', :to => "solutions#case_studies", :as => :case_studies , :via => :get
  match '/solutions/agile-infrastructure', :to => "solutions#agile_infrastructure", :as => :agile_infrastructure, :via => :get

app/models/cms/category.rb
class Cms::Category
  include Mongoid::Document
  include Mongoid::Slug
  field :title, type: String

  slug :title

  #embedded_in :resource, :inverse_of => 'categories'
end

app/models/cms/event.rb
class Cms::Event
  include Mongoid::Document
  include Mongoid::Slug

  field :title, type: String
  field :description, type: String
  field :start_date, type: Date
  field :end_date, type: Date
  field :location, type: String
  field :cta_title, type: String
  field :cta_url, type: String
  field :custom_image, type: String
  field :custom_image_id, type: String

  slug :title

end

app/models/cms/landing_page.rb
class Cms::LandingPage
  include Mongoid::Document
  include Mongoid::Slug

  field :title, type: String
  field :landing_title, type: String
  field :sub_title, type: String
  field :description, type: String
  field :asset_link, type: String
  field :mkto_form_id, type: String
  field :utube_id, type: String
  field :meta_title, type: String
  field :meta_description, type: String
  field :meta_no_follow, type: Integer
  field :thank_you_url, type: String
  field :layout_template, type: String
  field :custom_image, type: String
  field :custom_image_id, type: String
  field :form_description, type: String
  field :form_message, type: String
  field :login, type: Boolean
  field :vidyard_id, type: String

  slug :title

end

app/models/cms/layout_template.rb
class Cms::LayoutTemplate
  include Mongoid::Document
  field :name, type: String
  field :layout_file, type: String
end

app/models/cms/news.rb
class Cms::News
  include Mongoid::Document
  field :title, type: String
  field :url, type: String
  field :url_shorten, type: String
  field :pub_date, type: Date
  field :publication, type: String
end

app/models/cms/organic_landing.rb
class Cms::OrganicLanding
  include Mongoid::Document
  include Mongoid::Slug

  field :title, type: String
  field :sub_title, type: String
  field :cta_one, type: String
  field :cta_link_one, type: String
  field :cta_two, type: String
  field :cta_link_two, type: String
  field :cta_three, type: String
  field :cta_link_three, type: String
  field :body, type: String
  field :meta_title, type: String
  field :meta_description, type: String

  slug :title
end

app/models/cms/press_release.rb
class Cms::PressRelease
  include Mongoid::Document
  include Mongoid::Slug

  field :title, type: String
  field :sub_title, type: String
  field :body, type: String
  field :location, type: String
  field :pub_date, type: Date
  field :about, type: String
  field :short_url, type: String
  field :schedule_day, type: String
  field :schedule_time, type: String
  field :scheduled_release, type: String


  slug :title

end

app/models/cms/project_request.rb
class Cms::ProjectRequest
  include Mongoid::Document
  field :title, type: String
  field :description, type: String
  field :due_date, type: String
  field :pm_name, type: String
  field :pm_email, type: String
  field :client_email, type: String
  field :status, type: String
  field :additional_information, type: String
  field :type, type: String
  field :submit_date, type: Date
  field :archive, type: Integer
  field :jira_id, type: String
  field :other_info, type: String

  field :current_url, type: String
  field :new_url, type: String
  field :graphics_direction, type: String
  field :google_doc_graphics, type: String
  field :content_direction, type: String
  field :final_content_url, type: String

  field :seo_requirements, type: String
  field :priority, type: String
  field :url_examples, type: String

  field :graphic_type, type: String
  field :collateral_type, type: String

  field :audience, type: String
  field :graphic_guidelines, type: String
  field :creative_direction, type: String
  field :inspiration, type: String

  field :file_size, type: String
  field :bleed, type: String
  field :intended_use, type: String
  field :submit_final, type: String
  field :item, type: String

end

app/models/cms/project_request_item.rb
class Cms::ProjectRequestItem
  include Mongoid::Document
  field :name, type: String
  field :type_id, type: String
end

app/models/cms/project_request_status.rb
class Cms::ProjectRequestStatus
  include Mongoid::Document
  field :name, type: String
end

app/models/cms/project_request_type.rb
class Cms::ProjectRequestType
  include Mongoid::Document
  field :name, type: String
end

app/models/cms/section.rb
class Cms::Section
  include Mongoid::Document
  field :title, type: String
  field :url, type: String
end

app/models/cms/tag.rb
class Cms::Tag
  include Mongoid::Document
  include Mongoid::Slug

  field :title, type: String

  slug :title
 # embedded_in :resource, :inverse_of => :tags
end

app/controllers/cms/applications_controller.rb
class Cms::ApplicationsController < Cms::BaseController

end

app/controllers/cms/base_controller.rb
class Cms::BaseController < ApplicationController
	
  
end

app/controllers/cms/categories_controller.rb
class Cms::CategoriesController < ApplicationController
  before_action :set_cms_category, only: [:show, :edit, :update, :destroy]
  before_filter :check_login
  before_filter { |c| c.check_access '560085b9656237000d070000' }

  layout 'cms'

  # GET /cms/categories
  def index
    @cms_categories = Cms::Category.all
  end

  # GET /cms/categories/1
  def show
  end

  # GET /cms/categories/new
  def new
    @cms_category = Cms::Category.new
  end

  # GET /cms/categories/1/edit
  def edit
  end

  # POST /cms/categories
  def create
    @cms_category = Cms::Category.new(cms_category_params)

    if @cms_category.save
      redirect_to @cms_category, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cms/categories/1
  def update
    if @cms_category.update(cms_category_params)
      redirect_to @cms_category, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cms/categories/1
  def destroy
    @cms_category.destroy
    redirect_to cms_categories_url, notice: 'Category was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cms_category
      @cms_category = Cms::Category.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cms_category_params
      params.require(:cms_category).permit(:title)
    end
end

app/controllers/cms/events_controller.rb
class Cms::EventsController < ApplicationController
  before_action :set_cms_event, only: [:show, :edit, :update, :destroy]
  before_filter :check_login
  before_filter { |c| c.check_access '560083d7656237000d030000' }

  layout 'cms'

  # GET /cms/events
  def index
    @cms_events = Cms::Event.all.paginate(:page => params[:page], :per_page => 30)
  end

  # GET /cms/events/1
  def show
  end

  # GET /cms/events/new
  def new
    @cms_event = Cms::Event.new
  end

  # GET /cms/events/1/edit
  def edit
  end

  # POST /cms/events
  def create
    @cms_event = Cms::Event.new(cms_event_params)

    if @cms_event.save
      redirect_to @cms_event, notice: 'Event was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /cms/events/1
  def update
    if @cms_event.update(cms_event_params)
      redirect_to @cms_event, notice: 'Event was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /cms/events/1
  def destroy
    @cms_event.destroy
    redirect_to cms_events_url, notice: 'Event was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cms_event
      @cms_event = Cms::Event.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def cms_event_params
      params.require(:cms_event).permit(:title, :description, :start_date, :end_date, :location, :cta_title, :cta_url, :custom_image, :custom_image_id)
    end
end

app/views/cms/resources/_form.html.haml
= simple_form_for(@cms_resource) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title, :required => true
    = f.input :landing_title, :label => 'Landing page headline'
    = f.input :sub_title, :label => 'Landing page sub headline'
    = f.input :description, as: :text, :required => true
    = f.input :landing_description, as: :text, :label => 'Landing page description'
    = f.input :asset_link, :label => 'Link to asset'
    = f.input :mkto_form_id, :label => 'Marketo form id'
    = f.input :thank_you_url, :label => 'Thank you page URL'
    = f.input :utube_id, :label => 'YouTube video id'
    = f.input :vidyard_id, :label => 'Vidyard video id'
    = f.input :podcast_url, :label => 'Podcast URL'
  .radio-wrapper
    %p
      - if @cms_resource.custom_image_id?
        Current custom image
        = image_tag 'http://assets3.solidfire.com/uploads/resources/' + @cms_resource.custom_image_id + '-' + @cms_resource.custom_image
      - else
        Add custom image
      %input{:type => 'hidden', :id => 'cms_resource_custom_image', :name => 'cms_resource[custom_image]', :value => @cms_resource.custom_image}
      %input{:type => 'hidden', :id => 'cms_resource_custom_image_id', :name => 'cms_resource[custom_image_id]', :value => @cms_resource.custom_image_id}
    .display-images
  .add-image-wrapper
    .add-image-container
      .back-btn.margin-bottom-twenty-five
        %a{:herf => 'javascript://', :id => 'add-image-button', :class => 'cms-white-button'}
          - if @cms_resource.custom_image_id?
            update custom image
          - else
            add image
    - if @cms_resource.custom_image_id?
      .add-image-container
        .back-btn.margin-bottom-twenty-five
          = link_to 'remove custom image', 'javascript://', :class => 'button--grey', :id => 'remove-image-button'
  .radio-wrapper
    %p
      - if @is_edit == true
        Selected Categories
        %p
          - if @cms_cats_find
            - @cms_cats_find.each do |used_cat|
              %input{:type => 'checkbox', :name => 'cms_resource[cats][]', :value => used_cat.id, :id => 'cms_resource_cats_' + used_cat.id, :checked => true}
                = used_cat.title
        %p
          All Available Categories
        %p
          - if @is_edit == true
            - @cms_cats.each do |cats|
              %span{:id => cats.id}
                %input{:type => 'checkbox', :name => 'cms_resource[cats][]', :value => cats.id, :id => 'cms_resource_cats_' + cats.id}
                  = cats.title
      - else
        %p
          Categories
        - @cms_cats.each do |cats|
          %span
            %input{:type => 'checkbox', :name => 'cms_resource[cats][]', :value => cats.id, :id => 'cms_resource_cats_' + cats.id}
              = cats.title
  .radio-wrapper
    %p
      - if @is_edit == true
        Selected Types
        %p
          - if @cms_tags_find
            - @cms_tags_find.each do |used_tag|
              %input{:type => 'checkbox', :name => 'cms_resource[tags][]', :value => used_tag.id, :id => 'cms_resource_tags_' + used_tag.id, :checked => true}
                = used_tag.title

        %p
          All Available Types
        %p
          - if @is_edit == true
            - @cms_tags.each do |tags|
              %span{:id => tags.id}
                %input{:type => 'checkbox', :name => 'cms_resource[tags][]', :value => tags.id, :id => 'cms_resource_tags_' + tags.id}
                  = tags.title
      - else
        %p
          Types
        - @cms_tags.each do |tags|
          %span
            %input{:type => 'checkbox', :name => 'cms_resource[tags][]', :value => tags.id, :id => 'cms_resource_tags_' + tags.id}
              = tags.title
  .back-btn.margin-bottom-twenty-five
    = link_to 'meta tags', 'javascript://', :class => 'cms-white-button', :id => 'meta-tags-button'
  .form-inputs
    #meta-tags
      = f.input :meta_title
      = f.input :meta_description, as: :text
  .form-actions.submit-wrapper
    = f.button :submit, class: 'cms-red-button cms-form-button', style:"background-color: #e00000; font-size: 13px; padding: 9px 30px; line-height: 28px;"

app/views/cms/resources/all_resource_images.html.haml
.res-image-wrapper
  - @cms_resource_images.each do |res_image|
    .res-image-container
      %p
        = res_image.title
      %p
        = image_tag 'http://assets3.solidfire.com/uploads/resources/' + res_image.id + '-' + res_image.res_image_file_name
      %p
        .back-btn.margin-bottom-twenty-five
          %a{:href => 'javascript://', :class => 'cms-white-button image-select', :data => {:image_id => res_image.id, :image_name => res_image.res_image_file_name}}
            select image
      %p
        = @getImage
.hidden-fileds
  %input{:type => 'hidden', :id => 'current_page'}
  %input{:type => 'hidden', :id => 'show_per_page'}
  #page-navigation

app/views/cms/resources/edit.html.haml
.resources.project-request-index
  .resources__container.cms-margin-top
    .edit-user-top
      .user
        %p
          Editing
          = @cms_resource.title
      .link
        = link_to 'Manage Resources', cms_resources_path, :class => 'cms-white-button'


    = render 'form'

    .span12.border-top
      .button-container
        = link_to 'Manage Resources', cms_resources_path, :class => 'cms-white-button'

app/views/cms/resources/index.html.haml
.resources
  .resources__container.cms-margin-top
    %h3.float-left.cms-heading Resources

    .float-right.margin-bottom-twenty-five
      = link_to 'cms home', cms_home_index_path, :class => 'cms-white-button margin-right-fifteen'
      %a.cms-green-button{href: new_cms_resource_path}
        %span.plus +
        New Resource


    .record-wrapper.events
      .record-email
        %span.title Title
      .record-destroy
        &nbsp;

    - @cms_resources.each do |cms_resource|
      .custom-landing-item
        .record-email
          = cms_resource.title
        .record-destroy
          = link_to 'Destroy', cms_resource, :method => :delete, :data => { :confirm => 'Are you sure?' }, :class => 'destroy button--red--small'
          = link_to 'Edit', edit_cms_resource_path(cms_resource), :class => 'edit button--grey--small margin-right-fifteen'
          = link_to 'View', resources_path + '/' + cms_resource.slugs[0], :class => 'view button-light-blue-small margin-right-fifteen', :target => '_blank'
    .span12.border-top
      .button-container
        %a.cms-green-button{href: new_cms_resource_path}
          %span.plus +
          New Resource
      .button-container
        = link_to 'cms home', cms_home_index_path, :class => 'cms-white-button margin-right-fifteen'
      .button-container
        = link_to 'Change Resource Order', cms_resource_order_index_path, :class => 'cms-white-button margin-right-fifteen'
    .back-btn
      = will_paginate @cms_resources

app/views/cms/resources/new.html.haml
= content_for :javascript do
  = javascript_include_tag 'jquery.validate.min.js'

.resources.project-request-index
  .resources__container.cms-margin-top
    .edit-user-top
      .user
        %p Create new resource
      .link
        = link_to 'cms home', cms_home_index_path, :class => 'cms-white-button margin-right-fifteen'
        = link_to 'Manage Resources', cms_resources_path, :class => 'cms-white-button'

    = render 'form'

    .span12.border-top
      .button-container
        = link_to 'Manage Resources', cms_resources_path, :class => 'cms-white-button'
      .button-container
        = link_to 'cms home', cms_home_index_path, :class => 'cms-white-button margin-right-fifteen'

app/views/cms/resources/show.html.haml
.resources
  .resources__container
    %p
      %h2
        The resource
        = @cms_resource.title
        has been successfully created.
    .back-btn
      = link_to 'cms resources', cms_resources_path, :class => 'cms-red-button'